-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.START_DATE = "2.1.1"
NDefines.NGame.END_DATE = "9999.12.31"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "9999.12.31"
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.0005
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 10
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 6
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 6
NDefines.NCountry.PS_ADVANCE_TECH = 640
NDefines.NCountry.PS_BOOST_STABILITY = 120
NDefines.NCountry.PS_CHANGE_CULTURE = 20
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 60
NDefines.NCountry.REVOLT_TECH_IMPACT = 0.006
NDefines.NCountry.REVOLT_TECH_MORALE = 0.002
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_1_TECH = 56
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_TECH = 61
NDefines.NCountry.PROTECTORATE_TECH_THRESHOLD = 0.30
NDefines.NCountry.PRIMITIVES_TECH_MODIFIER = 0.5
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 49
NDefines.NCountry.TECHS_TO_REFORM = 153
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_RELIGION = 500
NDefines.NCountry.RAZE_TECH_BASE_LEVEL = 48
NDefines.NCountry.IDEA_TO_TECH = -0.01
NDefines.NCountry.TECH_TIME_COST = 1.0
NDefines.NCountry.LIBERTY_DESIRE_DEVELOPED_IN_SUBJECT = -1
NDefines.NCountry.ARMY_PROFESSIONALISM_PER_AGE = 0.04
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.002
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 56
NDefines.NAI.DEVELOPMENT_CAP_BASE = 500
NDefines.NAI.DEVELOPMENT_CAP_MULT = 5